name: build-documentation

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:

  run:
    runs-on: macos-ventura
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build documentation
      run: |
        scripts/build-documentation.sh

    - name: Publish documentation
      if: github.ref == 'refs/heads/main'
      uses: stefanzweifel/git-auto-commit-action@v4
      id: auto-commit
      with:
        branch: documentation
        create_branch: true
        push_options: --force
        commit_message: "docs: Update documentation"
