name: build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 1 * * *'

jobs:
  test:

    name: build
    runs-on: macOS-ventura

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: scripts/install-dependencies.sh

    - name: Build
      run: exec ./scripts/build.sh

    - name: Release
      # if: github.ref == 'refs/heads/main'
      run: scripts/release.sh
