name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 1 * * *'

jobs:
  test:

    name: Build package
    runs-on: macOS-ventura

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: exec ./scripts/build.sh
