name: update-documentation

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

  run:

    runs-on: macos-ventura

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build documentation
      run: |
        scripts/build-documentation.sh

    - name: Commit documentation
      uses: stefanzweifel/git-auto-commit-action@v4
      id: auto-commit
      with:
        branch: documentation
        create_branch: true
        commit_message: "docs: Update documentation"
